apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ratingdataservice
  name: ratingdataservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratingdataservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ratingdataservice
    spec:
      containers:
      - image: cycloides/ratingdataservice
        name: ratingdataservice
        resources: {}
status: {}
