apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ratingdataservice
  name: ratingdataservice
spec:
  ports:
  - name: 8085-8085
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: ratingdataservice
  type: NodePort
status:
  loadBalancer: {}
