apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: movie-catalog-service
build:
  artifacts:
  - image: cycloides/moviecatalogservice
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
