apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: movieinfoservice
  name: movieinfoservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieinfoservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: movieinfoservice
    spec:
      containers:
      - image: cycloides/movieinfoservice
        name: movieinfoservice
        resources: {}
status: {}
