apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: movieinfoservice
  name: movieinfoservice
spec:
  ports:
  - name: 8082-8082
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: movieinfoservice
  type: NodePort
status:
  loadBalancer: {}
